<template>
  <div class="loadingio-spinner-spinner-qy0bkgdren">
    <div class="flex items-center ldio-7tv322yx8dj">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-7tv322yx8dj {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-7tv322yx8dj div {
  left: 47.5px;
  top: 10px;
  position: absolute;
  animation: ldio-7tv322yx8dj linear 0.6097560975609756s infinite;
  background: #ffffff;
  width: 6px;
  height: 10px;
  border-radius: 2.16px / 2.16px;
  transform-origin: 6.5px 30.5px;
}
.ldio-7tv322yx8dj div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.5420054200542005s;
  background: #ffffff;
}
.ldio-7tv322yx8dj div:nth-child(2) {
  transform: rotate(40deg);
  animation-delay: -0.47425474254742545s;
  background: #ffffff;
}
.ldio-7tv322yx8dj div:nth-child(3) {
  transform: rotate(80deg);
  animation-delay: -0.40650406504065034s;
  background: #ffffff;
}
.ldio-7tv322yx8dj div:nth-child(4) {
  transform: rotate(120deg);
  animation-delay: -0.3387533875338753s;
  background: #ffffff;
}
.ldio-7tv322yx8dj div:nth-child(5) {
  transform: rotate(160deg);
  animation-delay: -0.27100271002710025s;
  background: #ffffff;
}
.ldio-7tv322yx8dj div:nth-child(6) {
  transform: rotate(200deg);
  animation-delay: -0.20325203252032517s;
  background: #ffffff;
}
.ldio-7tv322yx8dj div:nth-child(7) {
  transform: rotate(240deg);
  animation-delay: -0.13550135501355012s;
  background: #ffffff;
}
.ldio-7tv322yx8dj div:nth-child(8) {
  transform: rotate(280deg);
  animation-delay: -0.06775067750677506s;
  background: #ffffff;
}
.ldio-7tv322yx8dj div:nth-child(9) {
  transform: rotate(320deg);
  animation-delay: 0s;
  background: #ffffff;
}
.loadingio-spinner-spinner-qy0bkgdren {
  width: 30px;
  height: 20px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-7tv322yx8dj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.3);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-7tv322yx8dj div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
